'use client'

// Re-export all API hooks for convenience
export { useProducts, useProduct, useCreateProduct, useUpdateProduct, useDeleteProduct, productKeys } from './use-products'
export { useCategories, categoryKeys } from './use-categories'
export { useCart, useAddToCart, useUpdateCartItem, useRemoveCartItem, cartKeys } from './use-cart'
export { useOrders, useOrder, useCreateOrder, useUpdateOrderStatus, orderKeys } from './use-orders'
export { useReviews, useCreateReview, reviewKeys } from './use-reviews'
export { useChatRooms, useChatMessages, useSendMessage, useCreateChatRoom, chatKeys } from './use-chat'
export { useWishlist, useToggleWishlist, wishlistKeys } from './use-wishlist'
export { useWallet, useTopUpWallet, useWithdrawWallet, walletKeys } from './use-wallet'
export { useWithdrawals, useUpdateWithdrawal, withdrawalKeys } from './use-withdrawals'
export { useNotifications, useMarkNotificationRead, useMarkAllNotificationsRead, notificationKeys } from './use-notifications'
export { useVouchers, useValidateVoucher, voucherKeys } from './use-vouchers'
export { useAddresses, useAddAddress, useUpdateAddress, useDeleteAddress, addressKeys } from './use-addresses'
export { useSellerDashboard, sellerKeys } from './use-seller'
export { useAdminDashboard, useAdminUsers, useApproveProduct, useAdminWithdrawals, adminKeys } from './use-admin'
export { useUpload, useUploadMultiple } from './use-upload'
export { ApiProvider } from './provider'
